channels:
- conda-forge
dependencies:
- python=3.10.9
- pip<=23.3.2
- pip:
  - mlflow==2.10.0
  - cffi==1.16.0
  - cloudpickle==2.2.1
  - gmpy2==2.1.2
  - numpy==1.26.3
  - packaging==23.1
  - pandas==2.1.4
  - pyyaml==6.0.1
  - requests==2.31.0
  - torch==2.1.2
  - torchvision==0.16.2
name: mlflow-env
