upload_training_script_params:
  training_environment_name: mtg-artist-classification-training-gpu
  training_compute_name: GPU-CLUSTER
  experiment_name: mtg-artist-classification
  training_data_folder: azureml://subscriptions/94f3bfe4-d65b-4af2-959a-f4cc3f4fef6a/resourcegroups/john-cummings/workspaces/mtg-artist-classifier-dev/datastores/train_validaiton_images/paths/data/model_training_and_eval/train_images/
  validation_data_folder: azureml://subscriptions/94f3bfe4-d65b-4af2-959a-f4cc3f4fef6a/resourcegroups/john-cummings/workspaces/mtg-artist-classifier-dev/datastores/train_validaiton_images/paths/data/model_training_and_eval/val_images/
  batch_size: 4
  num_epochs: 25
download_params:
  model_download_location: downloaded_model/
  additional_non_torch_requirements:
    - gunicorn
    - flask
azure_ml:
  dev:
    service_principal_client_id: f57439fb-8a1f-4eb4-a047-b9733b900a07
    service_principal_tenant_id: e6ba44d9-c40a-4dc9-b59f-8fff330da1c0
    workspace_name: mtg-artist-classifier-dev
    azure_subscription_id: 94f3bfe4-d65b-4af2-959a-f4cc3f4fef6a
    resource_group_name: john-cummings