trigger:
  tags:
    include:
    - v*

pr: none

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install pipx
    pipx install poetry==1.4.2
    poetry install
    echo done with installation
  displayName: 'Install dependencies'

- script: |
    poetry run python cicd/deployment/download_model.py --config-file config.yaml --deployment-config-file cicd/deployment/config.yaml
    ls cicd/deployment/model
  displayName: 'Download Model'
  env:
    AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(94f3bfe4-d65b-4af2-959a-f4cc3f4fef6a)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az acr build --resource-group john-cummings --registry jtcmtgartistrecognizerdev --image mtg-classifier-dockerized:latest cicd/deployment' 