trigger:
  branches:
    include:
    - main
  paths:
    exclude:
      - cicd/deployment/**/*

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install pipx
    pipx install poetry==1.4.2
    poetry install
  displayName: 'Install dependencies'