trigger:
  branches:
    include:
    - main
  paths:
    exclude:
      - cicd/deployment/**
      - cicd/cd.yaml

pr: none

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install pipx
    pipx install poetry==1.4.2
    poetry install
  displayName: 'Install dependencies'

- script: |
    poetry run pytest
  displayName: 'pytest'

- script: |
    poetry run python cicd/upload_and_run_training_script.py --config-file config.yaml
  displayName: 'Train Model'
  env:
    AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
